`ifndef __FILEREG_H__
`define __FILEREG_H__

`define FILEREG_ENTRY_LBDR_VN0 0
`define FILEREG_ENTRY_LBDR_VN1 1
`define FILEREG_ENTRY_LBDR_VN2 2
`define FILEREG_ENTRY_LBDR_VN3 3
`define FILEREG_ENTRY_LBDR_VN4 4
`define FILEREG_ENTRY_5   5
`define FILEREG_ENTRY_6   6
`define FILEREG_ENTRY_7   7
`define FILEREG_ENTRY_8   8
`define FILEREG_ENTRY_9   9
`define FILEREG_ENTRY_10 10
`define FILEREG_ENTRY_11 11
`define FILEREG_ENTRY_12 12
`define FILEREG_ENTRY_13 13
`define FILEREG_ENTRY_14 14
`define FILEREG_ENTRY_15 15
`define FILEREG_NUMBER_OF_ENTRIES 16

`define FILEREG_COMMAND_READ  0
`define FILEREG_COMMAND_WRITE 1
`define FILEREG_NUMBER_OF_COMMANDS 2

`define FILEREG_ENTRY_WIDTH  32

`endif
