`ifndef __ROUTING_ALGORITHM_XY_H__
`define __ROUTING_ALGORITHM_XY_H__
 

`define XY_NUM_PORT_DIRECTIONS 5

`define XY_PORT_DIRECTION_INDEX_NORTH (3'd4)
`define XY_PORT_DIRECTION_INDEX_EAST  (3'd3)
`define XY_PORT_DIRECTION_INDEX_WEST  (3'd2)
`define XY_PORT_DIRECTION_INDEX_SOUTH (3'd1)
`define XY_PORT_DIRECTION_INDEX_LOCAL (3'd0)


`endif
